# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-08 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OAIField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OAIRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255)),
                ('datestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='OAIRepository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_id', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OAISet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_id', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=255)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oai.OAIRepository')),
            ],
        ),
        migrations.CreateModel(
            name='ResumptionToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('verb', models.CharField(max_length=64)),
                ('fro', models.DateTimeField(blank=True, null=True)),
                ('until', models.DateTimeField(blank=True, null=True)),
                ('cursor', models.IntegerField()),
                ('first_timestamp', models.DateTimeField()),
                ('key', models.CharField(blank=True, max_length=128, null=True)),
                ('set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oai.OAISet')),
            ],
        ),
        migrations.AddField(
            model_name='oairecord',
            name='sets',
            field=models.ManyToManyField(to='oai.OAISet'),
        ),
        migrations.AddField(
            model_name='oaifield',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oai.OAIRecord'),
        ),
    ]
