# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-28 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oaifield',
            name='value',
            field=models.TextField(),
        ),
    ]
